# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hardware',
            new_name='Machine',
        ),
    ]
