# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_manager', '0002_auto_20161002_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('slug', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
