# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine_manager', '0003_networkzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='zone',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='machine_in_nwzone', to='machine_manager.NetworkZone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_machine', to='machine_manager.HardwareType'),
        ),
    ]
