# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_manager', '0004_auto_20161002_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='puppetrepo',
            options={'ordering': ['name']},
        ),
    ]
