# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine_manager', '0005_auto_20161002_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineConnectMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_direction', models.CharField(choices=[('r', 'Read'), ('w', 'Write'), ('rw', 'Read/Write')], default='rw', max_length=2)),
                ('port', models.CommaSeparatedIntegerField(blank=True, default=None, max_length=150, null=True)),
                ('comment', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('from_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_machine_relation', to='machine_manager.Machine')),
                ('to_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_machine_relation', to='machine_manager.Machine')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='connected_to_machine',
            field=models.ManyToManyField(blank=True, default=None, related_name='machine_on_machine', through='machine_manager.MachineConnectMachine', to='machine_manager.Machine'),
        ),
        migrations.AlterUniqueTogether(
            name='machineconnectmachine',
            unique_together=set([('from_machine', 'to_machine', 'access_direction', 'port')]),
        ),
    ]
