# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_manager', '0006_auto_20161009_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='customer_accesable',
            field=models.BooleanField(default=False),
        ),
    ]
