# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 21:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('machine_manager', '0007_machine_customer_accesable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineconnectmachine',
            name='port',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
