# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_manager', '0008_auto_20161009_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['name'], 'permissions': (('is_owner', 'Is Owner'),)},
        ),
    ]
